[build]
builder = "nixpacks"
buildCommand = "pnpm build"

[deploy]
releaseCommand = "pnpm migrate:all"
startCommand = "pnpm migrate:all && pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "tiximo-api"
